import type { RecruitingEventSource } from "./repository.ts";

export const RECRUITING_EVENT_SOURCES: readonly RecruitingEventSource[] = Object.freeze([
  // Employers
  { id: "3m-careers-and-opportunities-for-students", name: "3M Careers and Opportunities for Students", url: "https://www.3m.com/3M/en_US/careers-us", category: "employer" },
  { id: "accenture-college-student-internship-other-student-programs", name: "Accenture — College Student Internship & Other Student Programs", url: "https://www.accenture.com/us-en/careers/life-at-accenture/internships-students", category: "employer" },
  { id: "activision-blizzard-early-careers-at-activision-press-play", name: "Activision Blizzard — Early Careers at Activision / Press Play", url: "https://careers.activision.com/early-careers", category: "employer" },
  { id: "adobe-careers-events", name: "Adobe Careers Events", url: "https://careers.adobe.com/us/en/events", category: "employer" },
  { id: "airbnb-connect-engineering-apprenticeship", name: "Airbnb — Connect Engineering Apprenticeship", url: "https://careers.airbnb.com/connect-engineering-apprenticeship", category: "employer" },
  { id: "akuna-students", name: "Akuna Capital student opportunities", url: "https://akunacapital.com/careers/students", category: "employer" },
  { id: "akuna-capital-internships", name: "Akuna Capital — Internships", url: "https://akunacapital.com/work-with-us/internships", category: "employer" },
  { id: "alaska-airlines-interns", name: "Alaska Airlines — Interns", url: "https://careers.alaskaair.com/career-opportunities/interns", category: "employer" },
  { id: "alvarez-marsal-early-careers", name: "Alvarez & Marsal — Early Careers", url: "https://careers.alvarezandmarsal.com/pages/early-careers", category: "employer" },
  { id: "amazon-university-talent-acquisition-auta", name: "Amazon University Talent Acquisition (AUTA)", url: "https://www.amazon.jobs/content/en/career-programs/university", category: "employer" },
  { id: "amd-student-programs-and-recruiting-events", name: "AMD — Student Programs and Recruiting Events", url: "https://www.amd.com/en/corporate/careers/student-programs.html", category: "employer" },
  { id: "amentum-early-careers", name: "Amentum — Early Careers", url: "https://www.amentumcareers.com/early-careers", category: "employer" },
  { id: "american-airlines-college", name: "American Airlines — College", url: "https://jobs.aa.com/content/college", category: "employer" },
  { id: "american-electric-power-aep-student-opportunities", name: "American Electric Power (AEP) — Student Opportunities", url: "https://www.aep.com/careers/students", category: "employer" },
  { id: "american-express-student-internships-graduate-opportunities", name: "American Express — Student Internships & Graduate Opportunities", url: "https://www.americanexpress.com/en-us/careers/student-programs/global-students-page.html", category: "employer" },
  { id: "amgen-scholars-program", name: "Amgen Scholars Program", url: "https://amgenscholars.com", category: "employer" },
  { id: "analog-devices-student-resources", name: "Analog Devices — Student Resources", url: "https://www.analog.com/en/about-adi/careers/student-resources.html", category: "employer" },
  { id: "anduril-early-careers", name: "Anduril — Early Careers", url: "https://www.anduril.com/early-careers", category: "employer" },
  { id: "anthropic-claude-campus-program", name: "Anthropic — Claude Campus Program", url: "https://claude.com/programs/campus", category: "employer" },
  { id: "aon-early-careers-launch-internships-apprenticeships", name: "Aon Early Careers (Launch, internships, apprenticeships)", url: "https://www.aon.com/en/careers", category: "employer" },
  { id: "apple-student-jobs-and-internships", name: "Apple Student Jobs and Internships", url: "https://www.apple.com/careers/us/work-at-apple/students.html", category: "employer" },
  { id: "applied-materials-students-and-early-career", name: "Applied Materials — Students and Early Career", url: "https://www.appliedmaterials.com/company/university", category: "employer" },
  { id: "argonne-national-laboratory-argonne-educational-programs-and-outreach", name: "Argonne National Laboratory — Argonne Educational Programs and Outreach", url: "https://www.anl.gov/education", category: "employer" },
  { id: "arm-emerging-talent", name: "Arm — Emerging Talent", url: "https://careers.arm.com/emerging-talent", category: "employer" },
  { id: "asanaup-university-recruiting", name: "AsanaUP University Recruiting", url: "https://asana.com/jobs/university-recruiting", category: "employer" },
  { id: "asml-students-and-new-graduates", name: "ASML — Students and New Graduates", url: "https://www.asml.com/careers/students-new-graduates", category: "employer" },
  { id: "astrazeneca-summer-internship-program-us", name: "AstraZeneca — Summer Internship Program (US)", url: "https://careers.astrazeneca.com/student-worker-and-internships-us", category: "employer" },
  { id: "at-t-hiring-events", name: "AT&T — Hiring Events", url: "https://www.att.jobs/events", category: "employer" },
  { id: "atlassian-early-careers", name: "Atlassian Early Careers", url: "https://www.atlassian.com/company/careers/earlycareers", category: "employer" },
  { id: "bae-systems-students-graduates-and-career-changers", name: "BAE Systems — Students, graduates and career changers", url: "https://careers.baesystems.com/students-graduates-and-career-changers", category: "employer" },
  { id: "bain-company-recruiting-events", name: "Bain & Company — Recruiting Events", url: "https://www.bain.com/careers/work-with-us/recruiting-events", category: "employer" },
  { id: "baker-hughes-early-careers", name: "Baker Hughes — Early Careers", url: "https://careers.bakerhughes.com/global/en/Early-Careers-BakerHughes", category: "employer" },
  { id: "bank-of-america-campus-experience", name: "Bank of America — Campus Experience", url: "https://careers.bankofamerica.com/en-us/students/campus-experience", category: "employer" },
  { id: "barclays-discovery-programme", name: "Barclays — Discovery Programme", url: "https://search.jobs.barclays/discovery", category: "employer" },
  { id: "best-buy-retail-summer-internship-program", name: "Best Buy — Retail Summer Internship Program", url: "https://corporate.bestbuy.com/2026/retail-internship-program", category: "employer" },
  { id: "biogen-student-programs", name: "Biogen — Student Programs", url: "https://www.biogen.com/careers/students-and-graduates.html", category: "employer" },
  { id: "blackrock-student-events", name: "BlackRock student events", url: "https://careers.blackrock.com/students-and-graduates-events", category: "employer" },
  { id: "blackrock-insight-learning-series", name: "BlackRock — Insight Learning Series", url: "https://careers.blackrock.com/students-and-graduates-apac-insight-learning-series", category: "employer" },
  { id: "block-builder-fellowship", name: "Block Builder Fellowship", url: "https://block.xyz/builder-fellowship", category: "employer" },
  { id: "bloomberg-events", name: "Bloomberg career events", url: "https://bloomberg.avature.net/events/EventsList", category: "employer" },
  { id: "bloomberg-early-careers", name: "Bloomberg Early Careers", url: "https://www.bloomberg.com/company/careers/early-careers", category: "employer" },
  { id: "bny-early-career-opportunities", name: "BNY — Early Career Opportunities", url: "https://www.bny.com/corporate/global/en/about-us/careers/students.html", category: "employer" },
  { id: "boeing-internships", name: "Boeing — Internships", url: "https://jobs.boeing.com/internships", category: "employer" },
  { id: "booking-holdings-booking-com-early-careers-compass", name: "Booking Holdings — Booking.com Early Careers / Compass", url: "https://careers.booking.com/early-careers", category: "employer" },
  { id: "booz-allen-hamilton-event-search", name: "Booz Allen Hamilton — Event Search", url: "https://careers.boozallen.com/events/EventsList", category: "employer" },
  { id: "bosch-career-opportunities", name: "Bosch — Career Opportunities", url: "https://www.bosch.com/careers/career-opportunities", category: "employer" },
  { id: "boston-consulting-group-bcg-careers-events", name: "Boston Consulting Group — BCG Careers Events", url: "https://careers.bcg.com/global/en/events", category: "employer" },
  { id: "bp-early-careers", name: "BP — Early Careers", url: "https://careers.bp.com/early-careers", category: "employer" },
  { id: "bristol-myers-squibb-events", name: "Bristol Myers Squibb career events", url: "https://careers.bms.com/events", category: "employer" },
  { id: "bristol-myers-squibb-student-opportunities", name: "Bristol Myers Squibb — Student Opportunities", url: "https://careers.bms.com/student-opportunities", category: "employer" },
  { id: "brookhaven-national-laboratory-bnl-workforce-development-and-science-education", name: "Brookhaven National Laboratory — BNL Workforce Development and Science Education", url: "https://www.bnl.gov/education", category: "employer" },
  { id: "canva-early-careers-launchpad-and-internship-program", name: "Canva Early Careers (Launchpad and Internship Program)", url: "https://www.lifeatcanva.com/en/early-careers", category: "employer" },
  { id: "capgemini-campus-activities", name: "Capgemini — Campus activities", url: "https://www.capgemini.com/gb-en/careers/lets-connect/campus-activities", category: "employer" },
  { id: "capital-one-events", name: "Capital One career events", url: "https://www.capitalonecareers.com/events", category: "employer" },
  { id: "capital-one-students-and-grads", name: "Capital One — Students and Grads", url: "https://www.capitalonecareers.com/students", category: "employer" },
  { id: "cboe-global-markets-careers-at-cboe", name: "Cboe Global Markets — Careers at Cboe", url: "https://careers.cboe.com/us/en/home", category: "employer" },
  { id: "cdw-students-recent-grads", name: "CDW — Students & Recent Grads", url: "https://www.cdwjobs.com/pages/student", category: "employer" },
  { id: "central-intelligence-agency-cia-student-programs", name: "Central Intelligence Agency — CIA Student Programs", url: "https://www.cia.gov/careers/student-programs", category: "employer" },
  { id: "cgi-innovate-it-challenge", name: "CGI Innovate IT Challenge", url: "https://www.cgi.com/en/article/esg/nurturing-student-talent-through-cgi-innovate-it-challenge", category: "employer" },
  { id: "charter-communications-spectrum-recruiting-events", name: "Charter Communications — Spectrum Recruiting Events", url: "https://jobs.spectrum.com/recruiting-events", category: "employer" },
  { id: "chevron-recruiting-events", name: "Chevron — Recruiting Events", url: "https://careers.chevron.com/events", category: "employer" },
  { id: "citadel-securities-programs-and-events", name: "Citadel Securities — Programs and Events", url: "https://www.citadelsecurities.com/careers/programs-and-events", category: "employer" },
  { id: "citadel-students", name: "Citadel student opportunities", url: "https://www.citadel.com/careers/students", category: "employer" },
  { id: "citadel-programs-events", name: "Citadel — Programs & Events", url: "https://www.citadel.com/careers/programs-and-events", category: "employer" },
  { id: "citi-events-pre-internships", name: "Citi — Events & Pre-Internships", url: "https://jobs.citi.com/events-preinternships", category: "employer" },
  { id: "cloudflare-early-talent-programs", name: "Cloudflare Early Talent Programs", url: "https://www.cloudflare.com/careers/early-talent", category: "employer" },
  { id: "coca-cola-a-role-for-everyone-early-careers", name: "Coca-Cola — A Role for Everyone — Early Careers", url: "https://www.coca-colacompany.com/careers/career-areas/a-role-for-everyone", category: "employer" },
  { id: "cognizant-lets-meet-at-a-cognizant-career-event", name: "Cognizant — Let’s meet at a Cognizant career event", url: "https://careers.cognizant.com/india-en/events", category: "employer" },
  { id: "cognizant-students-and-new-grads-careers", name: "Cognizant — Students and New Grads / Careers", url: "https://careers.cognizant.com/global-en", category: "employer" },
  { id: "colgate-palmolive-student-opportunities", name: "Colgate-Palmolive — Student Opportunities", url: "https://jobs.colgate.com/go/Student-Opportunities/8517500", category: "employer" },
  { id: "comcast-early-career-programs-internships-and-co-ops", name: "Comcast — Early Career Programs, Internships and Co-Ops", url: "https://jobs.comcast.com/early-career", category: "employer" },
  { id: "consumer-financial-protection-bureau-cfpb-students-and-graduates", name: "Consumer Financial Protection Bureau — CFPB Students and Graduates", url: "https://www.consumerfinance.gov/about-us/careers/students-and-graduates", category: "employer" },
  { id: "corning-early-career-programs", name: "Corning — Early Career Programs", url: "https://www.corning.com/worldwide/en/careers/early-career-programs.html", category: "employer" },
  { id: "crowdstrike-internship-university-programs", name: "CrowdStrike — Internship & University Programs", url: "https://www.crowdstrike.com/en-us/careers/university-interns", category: "employer" },
  { id: "csx-internship-programs", name: "CSX — Internship Programs", url: "https://www.csx.com/index.cfm/working-at-csx/job-overviews/internship-programs", category: "employer" },
  { id: "cvs-health-students-and-recent-graduates", name: "CVS Health — Students and Recent Graduates", url: "https://jobs.cvshealth.com/us/en/students", category: "employer" },
  { id: "cybersecurity-and-infrastructure-security-agency-cisa-events", name: "Cybersecurity and Infrastructure Security Agency — CISA Events", url: "https://www.cisa.gov/news-events/events", category: "employer" },
  { id: "cybersecurity-and-infrastructure-security-agency-cisa-students-and-recent-graduates-employment-opportunities", name: "Cybersecurity and Infrastructure Security Agency — CISA Students and Recent Graduates Employment Opportunities", url: "https://www.cisa.gov/careers/students-recent-graduates-employment-opportunities", category: "employer" },
  { id: "d-e-shaw-campus-recruiting", name: "D. E. Shaw — Campus Recruiting", url: "https://campus.deshaw.com", category: "employer" },
  { id: "databricks-internships-and-early-careers-university-program", name: "Databricks — Internships and Early Careers / University Program", url: "https://www.databricks.com/company/careers/university-recruiting", category: "employer" },
  { id: "datadog-early-career-internships", name: "Datadog — Early Career & Internships", url: "https://careers.datadoghq.com/early-careers", category: "employer" },
  { id: "dell-technologies-develop-with-dell-university-program", name: "Dell Technologies — Develop with Dell University Program", url: "https://learning.dell.com/content/dell/en-us/home/develop-with-dell.html", category: "employer" },
  { id: "deloitte-early-talent-events-programs", name: "Deloitte — Early Talent events & programs", url: "https://www.deloitte.com/ca/en/careers/explore-your-fit/students/campus-programs-and-events.html", category: "employer" },
  { id: "delta-air-lines-students-early-careers", name: "Delta Air Lines — Students & Early Careers", url: "https://delta.avature.net/en_US/careers/SearchJobs?jobOffset=0&jobLimit=10&jobCurrentPage=1&jobBoardId=1628&listFilterMode=1&jobPipeline=Students%20%26%20Early%20Careers", category: "employer" },
  { id: "department-of-homeland-security-dhs-student-opportunities", name: "Department of Homeland Security — DHS Student Opportunities", url: "https://www.dhs.gov/homeland-security-careers/students", category: "employer" },
  { id: "deutsche-bank-insight-programmes-events", name: "Deutsche Bank — Insight Programmes & Events", url: "https://careers.db.com/students-graduates/index?language_id=1", category: "employer" },
  { id: "docusign-university-new-grad", name: "DocuSign University & New Grad", url: "https://careers.docusign.com/students", category: "employer" },
  { id: "dominion-energy-student-employment", name: "Dominion Energy — Student Employment", url: "https://careers.dominionenergy.com/go/Student-Employment/3372900", category: "employer" },
  { id: "doordash-university-careers", name: "DoorDash — University Careers", url: "https://careersatdoordash.com/university-careers", category: "employer" },
  { id: "dropbox-emerging-talent", name: "Dropbox Emerging Talent", url: "https://www.dropbox.jobs/en/emerging-talent", category: "employer" },
  { id: "drw-students", name: "DRW student opportunities", url: "https://www.drw.com/work-at-drw/students", category: "employer" },
  { id: "drw-interns", name: "DRW — Interns", url: "https://www.drw.com/work-at-drw/interns", category: "employer" },
  { id: "duke-energy-opportunities-for-students", name: "Duke Energy — Opportunities for Students", url: "https://www.duke-energy.com/our-company/careers", category: "employer" },
  { id: "electronic-arts-early-careers-and-emerging-talent-programs", name: "Electronic Arts — Early Careers and Emerging Talent Programs", url: "https://www.ea.com/careers/early-careers", category: "employer" },
  { id: "elevance-health-early-student-opportunities", name: "Elevance Health — Early Student Opportunities", url: "https://careers.elevancehealth.com/early-student-opportunities", category: "employer" },
  { id: "eli-lilly-internships-at-lilly", name: "Eli Lilly — Internships at Lilly", url: "https://careers.lilly.com/us/en/internships", category: "employer" },
  { id: "entergy-internship-co-op-and-apprentice", name: "Entergy — Internship, Co-op and Apprentice", url: "https://jobs.entergy.com", category: "employer" },
  { id: "epic-games-epic-internships", name: "Epic Games — Epic Internships", url: "https://www.epicgames.com/site/earlycareers", category: "employer" },
  { id: "equinix-global-internship-program", name: "Equinix — Global Internship Program", url: "https://careers.equinix.com/global-internship", category: "employer" },
  { id: "ericsson-students-and-early-careers", name: "Ericsson — Students and Early Careers", url: "https://www.ericsson.com/en/careers/students-early-careers", category: "employer" },
  { id: "estee-lauder-companies-student-internships", name: "Estée Lauder Companies — Student Internships", url: "https://www.elcompanies.com/en/careers/students/internships", category: "employer" },
  { id: "exelon-foundation-boys-to-stem-academy", name: "Exelon Foundation Boys to STEM Academy", url: "https://exelonstemacademy.org/boys-academy", category: "employer" },
  { id: "expedia-group-emerging-talent-careers", name: "Expedia Group — Emerging Talent & Careers", url: "https://careers.expediagroup.com/emerging-talent-and-careers", category: "employer" },
  { id: "exxonmobil-u-s-internship-opportunities", name: "ExxonMobil — U.S. Internship Opportunities", url: "https://corporate.exxonmobil.com/careers/internship-opportunities", category: "employer" },
  { id: "ey-next-steps-events-hub", name: "EY Next Steps events hub", url: "https://www.ey.com/en_us/careers/virtual-events-for-students", category: "employer" },
  { id: "federal-bureau-of-investigation-fbi-jobs-students-and-graduates", name: "Federal Bureau of Investigation — FBI Jobs Students and Graduates", url: "https://fbijobs.gov/students-and-graduates", category: "employer" },
  { id: "federal-deposit-insurance-corporation-fdic-corporate-outreach-recruitment-events", name: "Federal Deposit Insurance Corporation — FDIC Corporate Outreach Recruitment Events", url: "https://www.fdic.gov/careers/corporate-outreach-recruitment-events", category: "employer" },
  { id: "federal-deposit-insurance-corporation-fdic-on-campus-recruiting", name: "Federal Deposit Insurance Corporation — FDIC On-Campus Recruiting", url: "https://www.fdic.gov/careers/campus-recruiting", category: "employer" },
  { id: "federal-reserve-board-internships", name: "Federal Reserve Board Internships", url: "https://www.federalreserve.gov/careers-internships.htm", category: "employer" },
  { id: "federal-reserve-board-exploring-careers-in-economics", name: "Federal Reserve Board — Exploring Careers in Economics", url: "https://www.federalreserve.gov/conferences/exploring-careers-in-economics.htm", category: "employer" },
  { id: "fedex-student-programs-internships", name: "FedEx — Student Programs & Internships", url: "https://careers.fedex.com/career-areas/student-programs", category: "employer" },
  { id: "fermilab-internships", name: "Fermilab Internships", url: "https://internships.fnal.gov", category: "employer" },
  { id: "fidelity-investments-students-and-early-career-opportunities", name: "Fidelity Investments — Students and Early Career Opportunities", url: "https://jobs.fidelity.com/en/students", category: "employer" },
  { id: "fis-university-program-internships", name: "FIS University Program & Internships", url: "https://careers.fisglobal.com/us/en/c/fis-university-programinterns-jobs", category: "employer" },
  { id: "fiserv-students-graduates", name: "Fiserv Students & Graduates", url: "https://careers.fiserv.com/us/en/students", category: "employer" },
  { id: "ford-student-and-graduate-careers", name: "Ford — Student and Graduate Careers", url: "https://www.careers.ford.com/students-graduates", category: "employer" },
  { id: "fortinet-academic-partner-program", name: "Fortinet — Academic Partner Program", url: "https://www.fortinet.com/training/academic-partner-program", category: "employer" },
  { id: "fox-internship-program", name: "FOX Internship Program", url: "https://www.foxcareers.com/internships", category: "employer" },
  { id: "ge-aerospace-students-and-new-graduates", name: "GE Aerospace — Students and New Graduates", url: "https://careers.geaerospace.com/global/en/global-students-new-graduates", category: "employer" },
  { id: "ge-healthcare-students-and-graduates", name: "GE HealthCare — Students and Graduates", url: "https://jobs.gehealthcare.com/global/en/students-graduates", category: "employer" },
  { id: "ge-vernova-early-careers", name: "GE Vernova — Early Careers", url: "https://careers.gevernova.com/early-careers", category: "employer" },
  { id: "general-dynamics-gdit-early-talent-career-portal", name: "General Dynamics — GDIT Early Talent Career Portal", url: "https://gdit.wd5.myworkdayjobs.com/GDIT_EarlyTalent", category: "employer" },
  { id: "general-mills-university-internships", name: "General Mills — University & Internships", url: "https://www.careers.generalmills.com", category: "employer" },
  { id: "general-motors-gm-early-careers", name: "General Motors — GM Early Careers", url: "https://search-careers.gm.com/en/early-careers", category: "employer" },
  { id: "gilead-early-career-opportunities", name: "Gilead — Early Career Opportunities", url: "https://www.gilead.com/careers/opportunities/early-career-opportunities", category: "employer" },
  { id: "github-campus-experts", name: "GitHub Campus Experts", url: "https://github.com/education/students/campus-expert", category: "employer" },
  { id: "globalfoundries-early-career", name: "GlobalFoundries — Early Career", url: "https://gf.com/careers/early-career", category: "employer" },
  { id: "goldman-sachs-events", name: "Goldman Sachs student programs", url: "https://www.goldmansachs.com/careers/students/programs-and-internships", category: "employer" },
  { id: "goldman-sachs-asia-possibilities-series", name: "Goldman Sachs — Asia Possibilities Series", url: "https://www.goldmansachs.com/careers/students/programs-and-internships/asia-pacific/asia-possibilities-series", category: "employer" },
  { id: "google-careers-onair", name: "Google Careers OnAir", url: "https://careersonair.withgoogle.com", category: "employer" },
  { id: "google-student-events", name: "Google student events", url: "https://buildyourfuture.withgoogle.com/events", category: "employer" },
  { id: "guidehouse-early-career-internships", name: "Guidehouse — Early career & internships", url: "https://guidehouse.com/careers/students", category: "employer" },
  { id: "halliburton-careers-at-halliburton", name: "Halliburton — Careers at Halliburton", url: "https://careers.halliburton.com", category: "employer" },
  { id: "hilton-student-early-career-paths", name: "Hilton — Student & early career paths", url: "https://jobs.hilton.com/early-career-paths", category: "employer" },
  { id: "home-depot-students-internships", name: "Home Depot — Students/Internships", url: "https://careers.homedepot.com/students-internships", category: "employer" },
  { id: "hp-internships-graduates-and-alternative-pathways", name: "HP Internships, Graduates and Alternative Pathways", url: "https://jobs.hp.com", category: "employer" },
  { id: "hsbc-students-and-graduates-career-events", name: "HSBC — Students and Graduates Career Events", url: "https://www.hsbc.com/careers/students-and-graduates/events", category: "employer" },
  { id: "hubspot-emerging-talent", name: "HubSpot Emerging Talent", url: "https://www.hubspot.com/careers/emerging-talent", category: "employer" },
  { id: "hudson-river-trading-student-opportunities", name: "Hudson River Trading — Student Opportunities", url: "https://www.hudsonrivertrading.com/student-opportunities", category: "employer" },
  { id: "humana-student-and-early-career-programs", name: "Humana — Student and Early Career Programs", url: "https://careers.humana.com/us/en/students-professional-programs", category: "employer" },
  { id: "hyatt-risehy-career-journey", name: "Hyatt — RiseHY Career Journey", url: "https://www.hyatt.com/world-of-care/en-US/risehy/career-journey", category: "employer" },
  { id: "ibm-internships", name: "IBM Internships", url: "https://www.ibm.com/careers/internships", category: "employer" },
  { id: "ibm-z-skills-fest", name: "IBM Z Skills Fest", url: "https://www.ibm.com/community/z/skillsfest", category: "employer" },
  { id: "idaho-national-laboratory-inl-internship-opportunities", name: "Idaho National Laboratory — INL Internship Opportunities", url: "https://inl.gov/internships", category: "employer" },
  { id: "idaho-national-laboratory-inl-university-recruiting", name: "Idaho National Laboratory — INL University Recruiting", url: "https://inl.gov/education/university-recruiting", category: "employer" },
  { id: "imc-student-events", name: "IMC Trading — IMC student events", url: "https://www.imc.com/us/careers/students-graduates/events", category: "employer" },
  { id: "imc-trading-launchpad", name: "IMC Trading — Launchpad", url: "https://www.imc.com/us/careers/students-graduates/programs/launchpad", category: "employer" },
  { id: "infosys-instep-global-internship", name: "Infosys — InStep global internship", url: "https://www.infosys.com/instep.html", category: "employer" },
  { id: "insight-enterprises-early-career-programs-internships-co-ops", name: "Insight Enterprises — Early Career Programs (Internships & Co-ops)", url: "https://www.insight.com/en_US/careers/united-states/early-career-programs.html", category: "employer" },
  { id: "instacart-associate-product-manager-program", name: "Instacart — Associate Product Manager Program", url: "https://www.instacart.careers/apm", category: "employer" },
  { id: "intercontinental-exchange-ice-intern-program", name: "Intercontinental Exchange — ICE Intern Program", url: "https://www.ice.com/careers/intern", category: "employer" },
  { id: "intuit-internships-co-ops", name: "Intuit Internships & Co-ops", url: "https://www.intuit.com/careers/programs/internships", category: "employer" },
  { id: "jane-street-our-programs-and-events", name: "Jane Street — Our Programs and Events", url: "https://www.janestreet.com/join-jane-street/programs-and-events", category: "employer" },
  { id: "jetblue-emerging-talent-jet-program", name: "JetBlue Emerging Talent / JET Program", url: "https://careers.jetblue.com/content/People-and-Culture?locale=en_US", category: "employer" },
  { id: "john-deere-internships", name: "John Deere Internships", url: "https://www.deere.co.uk/en-gb/our-company/careers/internships", category: "employer" },
  { id: "johns-hopkins-apl-recruiting-events", name: "Johns Hopkins APL — Recruiting Events", url: "https://www.jhuapl.edu/careers/recruiting-events", category: "employer" },
  { id: "johnson-johnson-early-career-programs", name: "Johnson & Johnson — Early-career programs", url: "https://www.careers.jnj.com/en/early-career-programs", category: "employer" },
  { id: "jpmorgan-chase-careers-events", name: "JPMorgan Chase — Careers Events", url: "https://www.jpmorganchase.com/careers/events", category: "employer" },
  { id: "jpmorgan-student-events", name: "JPMorganChase student events", url: "https://careers.jpmorgan.com/us/en/students/events", category: "employer" },
  { id: "jump-trading-students-new-grads", name: "Jump Trading — Students & New Grads", url: "https://www.jumptrading.com/hr/students-new-grads", category: "employer" },
  { id: "keysight-technologies-students-and-graduates", name: "Keysight Technologies — Students and Graduates", url: "https://www.keysight.com/us/en/about/careers/students-and-graduates.html", category: "employer" },
  { id: "kimberly-clark-intern-or-new-grad", name: "Kimberly-Clark — Intern or New Grad", url: "https://careers.kimberly-clark.com/en", category: "employer" },
  { id: "kpmg-early-career-student-opportunities", name: "KPMG — Early Career & Student Opportunities", url: "https://www.kpmguscareers.com/early-career", category: "employer" },
  { id: "kraft-heinz-early-careers", name: "Kraft Heinz — Early Careers", url: "https://careers.kraftheinzcompany.com/early-careers", category: "employer" },
  { id: "kyndryl-early-careers", name: "Kyndryl — Early careers", url: "https://www.kyndryl.com/us/en/careers/early-careers", category: "employer" },
  { id: "l-oreal-students", name: "L'Oréal — Students", url: "https://careers.loreal.com/jobs/Students", category: "employer" },
  { id: "l3harris-working-at-l3harris-technologies-global-events", name: "L3Harris — Working at L3Harris Technologies — Global Events", url: "https://careers.l3harris.com/en", category: "employer" },
  { id: "lam-research-university-programs", name: "Lam Research — University Programs", url: "https://www.lamresearch.com/careers/university-programs", category: "employer" },
  { id: "lawrence-livermore-national-laboratory-events-resources", name: "Lawrence Livermore National Laboratory — Events & Resources", url: "https://www.llnl.gov/join-our-team/careers/events-resources", category: "employer" },
  { id: "leidos-intern-jobs", name: "Leidos — Intern Jobs", url: "https://careers.leidos.com/pages/intern-jobs", category: "employer" },
  { id: "linkedin-pathways-programs", name: "LinkedIn Pathways & Programs", url: "https://careers.linkedin.com/pathways-programs", category: "employer" },
  { id: "lockheed-martin-events", name: "Lockheed Martin career events", url: "https://www.lockheedmartin.com/en-us/careers/events.html", category: "employer" },
  { id: "lockheed-martin-high-school-programs", name: "Lockheed Martin — High School Programs", url: "https://www.lockheedmartin.com/en-us/careers/candidates/students-early-careers/high-school.html", category: "employer" },
  { id: "los-alamos-national-laboratory-student-programs", name: "Los Alamos National Laboratory — Student Programs", url: "https://www.lanl.gov/engage/collaboration/student-programs", category: "employer" },
  { id: "lowe-s-students-grads-summer-internship-program", name: "Lowe's — Students & Grads / Summer Internship Program", url: "https://talent.lowes.com/us/en/students-and-grads", category: "employer" },
  { id: "lyft-early-talent-programs", name: "Lyft — Early Talent Programs", url: "https://www.lyft.com/careers/early-talent", category: "employer" },
  { id: "maersk-student-and-graduate-schemes", name: "Maersk — Student and Graduate Schemes", url: "https://www.maersk.com/careers/our-teams/students-graduates", category: "employer" },
  { id: "marriott-early-careers", name: "Marriott — Early Careers", url: "https://careers.marriott.com/career-journeys/early-careers", category: "employer" },
  { id: "mars-students-graduates", name: "Mars — Students & Graduates", url: "https://careers.mars.com/us/en/students-graduates", category: "employer" },
  { id: "mastercard-early-careers", name: "Mastercard Early Careers", url: "https://careers.mastercard.com/us/en/early-careers", category: "employer" },
  { id: "mckinsey-company-recruiting-events", name: "McKinsey & Company — Recruiting Events", url: "https://www.mckinsey.com/careers/events", category: "employer" },
  { id: "medtronic-early-careers", name: "Medtronic — Early Careers", url: "https://www.medtronic.com/en-us/our-company/careers/early-careers.html", category: "employer" },
  { id: "merck-u-s-future-talent-program", name: "Merck — U.S. Future Talent Program", url: "https://jobs.merck.com/us/en/student-opportunities", category: "employer" },
  { id: "meta-jobs-for-students-recent-grads", name: "Meta — Jobs for Students & Recent Grads", url: "https://www.metacareers.com/careerprograms/students", category: "employer" },
  { id: "metlife-university-development-programs", name: "MetLife University & Development Programs", url: "https://www.metlifecareers.com/en_US/ml/EarlyCareer", category: "employer" },
  { id: "micron-technology-university-recruiting", name: "Micron Technology — University Recruiting", url: "https://www.micron.com/about/careers/university-recruiting", category: "employer" },
  { id: "microsoft-events", name: "Microsoft university virtual events", url: "https://careers.microsoft.com/v2/global/en/virtualevents", category: "employer" },
  { id: "microsoft-early-in-profession-students", name: "Microsoft — Early in Profession / Students", url: "https://careers.microsoft.com/v2/global/en/programs/students.html", category: "employer" },
  { id: "mitre-student-career-programs", name: "MITRE — Student Career Programs", url: "https://careers.mitre.org/us/en/student-programs", category: "employer" },
  { id: "moderna-mba-internship-program-early-career-programs", name: "Moderna — MBA Internship Program / Early Career Programs", url: "https://www.modernatx.com/media-center/all-media/blogs/leading-moderna-into-the-future", category: "employer" },
  { id: "mondelez-international-early-careers", name: "Mondelēz International — Early Careers", url: "https://www.mondelezinternational.com/Careers/Early-Careers", category: "employer" },
  { id: "mongodb-students-graduates", name: "MongoDB Students & Graduates", url: "https://www.mongodb.com/company/careers/students-and-graduates", category: "employer" },
  { id: "moody-s-early-careers-programs", name: "Moody's Early Careers Programs", url: "https://careers.moodys.com/en", category: "employer" },
  { id: "morgan-stanley-events", name: "Morgan Stanley student events", url: "https://www.morganstanley.com/people-opportunities/students-graduates/events", category: "employer" },
  { id: "morgan-stanley-career-events-search", name: "Morgan Stanley — Career Events Search", url: "https://www.morganstanley.com/careers/events-aggregate", category: "employer" },
  { id: "nasa-internship-programs", name: "NASA Internship Programs", url: "https://www.nasa.gov/learning-resources/internship-programs", category: "employer" },
  { id: "nasdaq-internship-program", name: "Nasdaq Internship Program", url: "https://www.nasdaq.com/about/careers/nasdaq-internship-program", category: "employer" },
  { id: "national-institute-of-standards-and-technology-nist-student-employment", name: "National Institute of Standards and Technology — NIST Student Employment", url: "https://www.nist.gov/careers/student-opportunities", category: "employer" },
  { id: "national-renewable-energy-laboratory-nrel-careers", name: "National Renewable Energy Laboratory — NREL Careers", url: "https://www.nrel.gov/careers", category: "employer" },
  { id: "national-science-foundation-nsf-students-and-recent-grads", name: "National Science Foundation — NSF Students and Recent Grads", url: "https://www.nsf.gov/careers/job-types/students-and-recent-grads", category: "employer" },
  { id: "national-security-agency-nsa-careers-student-programs", name: "National Security Agency — NSA Careers Student Programs", url: "https://www.nsa.gov/Careers/Student-Programs", category: "employer" },
  { id: "nationwide-internships-and-university-relations", name: "Nationwide Internships and University Relations", url: "https://www.nationwide.com/personal/about-us/careers/types/college", category: "employer" },
  { id: "nbcuniversal-internships", name: "NBCUniversal Internships", url: "https://www.nbcunicareers.com/internships", category: "employer" },
  { id: "netapp-early-in-career-netapp-emerging-talent-program", name: "NetApp — Early in Career / NetApp Emerging Talent Program", url: "https://careers.netapp.com/entry-level-careers", category: "employer" },
  { id: "new-york-life-student-internships", name: "New York Life Student Internships", url: "https://www.newyorklife.com/careers/corporate/internships", category: "employer" },
  { id: "nextera-energy-internships", name: "NextEra Energy — Internships", url: "https://www.nexteraenergy.com/careers/join-our-team/internships.html", category: "employer" },
  { id: "nike-internships", name: "Nike Internships", url: "https://careers.nike.com/career-areas", category: "employer" },
  { id: "norfolk-southern-internships", name: "Norfolk Southern — Internships", url: "https://www.norfolksouthern.com/en/careers/find-your-future/internships", category: "employer" },
  { id: "northrop-grumman-internships-at-northrop-grumman", name: "Northrop Grumman — Internships at Northrop Grumman", url: "https://www.northropgrumman.com/careers/internships-at-northrop-grumman", category: "employer" },
  { id: "novartis-us-biomedical-research-internship-programs", name: "Novartis — US Biomedical Research Internship Programs", url: "https://www.novartis.com/careers/early-careers/us-biomedical-research-internship-programs", category: "employer" },
  { id: "ntt-data-campus-to-career-recent-graduate-and-entry-level-jobs", name: "NTT DATA — Campus to Career / Recent Graduate and Entry Level Jobs", url: "https://careers-inc.nttdata.com/default/go/Recent-Graduate-and-Entry-Level-Jobs/3019900", category: "employer" },
  { id: "nvidia-university-recruiting-event-calendar", name: "NVIDIA — University Recruiting Event Calendar", url: "https://www.nvidia.com/en-us/about-nvidia/careers/university-recruiting/events-calendar", category: "employer" },
  { id: "oak-ridge-national-laboratory-ornl-events-and-information-sessions", name: "Oak Ridge National Laboratory — ORNL Events and Information Sessions", url: "https://www.ornl.gov/content/events-information-sessions", category: "employer" },
  { id: "occidental-petroleum-oxy-students-and-recent-graduates", name: "Occidental Petroleum (Oxy) — Students and Recent Graduates", url: "https://www.oxy.com/careers/explore-careers/students", category: "employer" },
  { id: "oliver-wyman-recruiting-events-and-initiatives", name: "Oliver Wyman — Recruiting Events And Initiatives", url: "https://www.oliverwyman.com/careers/recruiting-events.html", category: "employer" },
  { id: "openai-emerging-talent-community-and-programs", name: "OpenAI — Emerging Talent Community and Programs", url: "https://openai.com/careers/emerging-talent", category: "employer" },
  { id: "optiver-programs", name: "Optiver — Programs", url: "https://www.optiver.com/join-us/students/programs", category: "employer" },
  { id: "oracle-students-and-graduates", name: "Oracle Students and Graduates", url: "https://www.oracle.com/careers/students-grads", category: "employer" },
  { id: "pacific-northwest-national-laboratory-discover-careers-at-pnnl-virtual-information-sessions", name: "Pacific Northwest National Laboratory — Discover Careers at PNNL Virtual Information Sessions", url: "https://www.pnnl.gov/events/discover-careers-pnnl-virtual-information-sessions", category: "employer" },
  { id: "pacific-northwest-national-laboratory-pnnl-internships", name: "Pacific Northwest National Laboratory — PNNL Internships", url: "https://www.pnnl.gov/internships", category: "employer" },
  { id: "palantir-students-and-early-talent", name: "Palantir — Students and Early Talent", url: "https://www.palantir.com/careers/students-and-early-talent", category: "employer" },
  { id: "palo-alto-networks-early-careers-internship-and-leap-programs", name: "Palo Alto Networks — Early Careers / Internship and LEAP Programs", url: "https://jobs.paloaltonetworks.com/en/early-in-career", category: "employer" },
  { id: "paramount-internships-early-career-roles", name: "Paramount — Internships & Early Career Roles", url: "https://www.paramount.com/careers/internships", category: "employer" },
  { id: "paypal-university-hiring-intern-hub", name: "PayPal — University Hiring – Intern Hub", url: "https://careers.pypl.com/university-hiring/Intern-Hub/default.aspx", category: "employer" },
  { id: "pepsico-internships-programs", name: "PepsiCo — Internships & Programs", url: "https://www.pepsicojobs.com/internshipsprograms", category: "employer" },
  { id: "pfizer-early-careers", name: "Pfizer Early Careers", url: "https://www.pfizer.com/en/about/careers/early-careers", category: "employer" },
  { id: "pg-e-university-programs", name: "PG&E — University Programs", url: "https://jobs.pge.com/university-programs", category: "employer" },
  { id: "phillips-66-students-graduates", name: "Phillips 66 — Students & Graduates", url: "https://careers.phillips66.com/content/Students-and-Graduates?locale=en_US", category: "employer" },
  { id: "plaid-careers-launch-your-career-with-plaid", name: "Plaid — Careers (Launch Your Career with Plaid)", url: "https://plaid.com/careers", category: "employer" },
  { id: "pnc-early-career-opportunities", name: "PNC — Early Career Opportunities", url: "https://careers.pnc.com/global/en/students", category: "employer" },
  { id: "procter-gamble-standout-emerging-leaders", name: "Procter & Gamble — Standout Emerging Leaders", url: "https://www.pgcareers.com/us/en/Standout-Emerging-Leaders", category: "employer" },
  { id: "progressive-internships-for-college-students", name: "Progressive Internships for College Students", url: "https://careers.progressive.com/pages/students-graduates-internships", category: "employer" },
  { id: "prudential-financial-prudential-student-programs-early-talent", name: "Prudential Financial — Prudential Student Programs / Early Talent", url: "https://jobs.prudential.com/us-en/early-talent", category: "employer" },
  { id: "pwc-us-entry-level-careers", name: "PwC — US Entry Level careers", url: "https://jobs.us.pwc.com/entry-level", category: "employer" },
  { id: "qualcomm-internships-and-early-in-career-opportunities", name: "Qualcomm — Internships and Early-in-Career Opportunities", url: "https://www.qualcomm.com/company/careers/internships-and-early-in-career-opportunities", category: "employer" },
  { id: "regeneron-early-careers", name: "Regeneron — Early Careers", url: "https://careers.regeneron.com/en/career-pathways/early-careers", category: "employer" },
  { id: "riot-games-emerging-talent-programs", name: "Riot Games — Emerging Talent Programs", url: "https://www.riotgames.com/en/student-internships", category: "employer" },
  { id: "rivian-students", name: "Rivian Students", url: "https://careers.rivian.com/students", category: "employer" },
  { id: "robinhood-early-talent", name: "Robinhood — Early Talent", url: "https://robinhood.com/us/en/careers/early-talent", category: "employer" },
  { id: "roblox-early-career-and-virtual-events", name: "Roblox — Early Career and Virtual Events", url: "https://careers.roblox.com/early-career", category: "employer" },
  { id: "roche-student-and-graduate-programmes", name: "Roche — Student and Graduate Programmes", url: "https://careers.roche.com/global/en/student-and-graduate-programs", category: "employer" },
  { id: "rocket-lab-internships", name: "Rocket Lab — Internships", url: "https://rocketlabcorp.com/careers/internships", category: "employer" },
  { id: "roland-berger-events-meet-us", name: "Roland Berger — Events / Meet us", url: "https://www.rolandberger.com/en/Join/All-Events", category: "employer" },
  { id: "rtx-campus-programs", name: "RTX — Campus Programs", url: "https://careers.rtx.com/global/en/campusprograms", category: "employer" },
  { id: "s-p-global-careers-events", name: "S&P Global Careers Events", url: "https://www.spglobal.com/en/careers/events", category: "employer" },
  { id: "saic-early-career-and-internships", name: "SAIC — Early Career and Internships", url: "https://jobs.saic.com/pages/early-career", category: "employer" },
  { id: "salesforce-futureforce-university-recruiting", name: "Salesforce — Futureforce University Recruiting", url: "https://www.salesforce.com/company/careers/university", category: "employer" },
  { id: "sandia-national-laboratories-internships-co-ops", name: "Sandia National Laboratories — Internships & Co-ops", url: "https://www.sandia.gov/careers/careers/students-and-postdocs/internships-co-ops", category: "employer" },
  { id: "sanofi-early-talent", name: "Sanofi — Early Talent", url: "https://jobs.sanofi.com/en/early-talent", category: "employer" },
  { id: "scale-ai-university-student-careers-university-program", name: "Scale AI — University Student Careers / University Program", url: "https://scale.com/careers/university", category: "employer" },
  { id: "schneider-electric-early-careers", name: "Schneider Electric — Early Careers", url: "https://careers.se.com/early-careers", category: "employer" },
  { id: "seagate-university-programs", name: "Seagate — University Programs", url: "https://www.seagate.com/jobs/university-programs", category: "employer" },
  { id: "servicenow-early-careers", name: "ServiceNow Early Careers", url: "https://careers.servicenow.com/early-careers", category: "employer" },
  { id: "shell-early-careers", name: "Shell — Early Careers", url: "https://www.shell.com/careers/about-careers-at-shell/early-careers.html", category: "employer" },
  { id: "shopify-engineering-data-internship-program", name: "Shopify — Engineering & Data Internship Program", url: "https://internships.shopify.com", category: "employer" },
  { id: "sierra-space-internship-program", name: "Sierra Space Internship Program", url: "https://www.sierraspace.com/careers/internship", category: "employer" },
  { id: "slb-early-careers", name: "SLB — Early Careers", url: "https://careers.slb.com/early-careers", category: "employer" },
  { id: "snap-academies", name: "Snap Academies", url: "https://www.snapacademies.com", category: "employer" },
  { id: "snowflake-university-recruiting", name: "Snowflake University Recruiting", url: "https://careers.snowflake.com/university", category: "employer" },
  { id: "sofi-the-intern-experience-at-sofi-technologies", name: "SoFi — The Intern Experience at SoFi Technologies", url: "https://sofietyinfo.sofi.com/intern-experience", category: "employer" },
  { id: "sony-internships", name: "Sony Internships", url: "https://www.sonyjobs.com/internships.html", category: "employer" },
  { id: "southern-company-campus-home", name: "Southern Company — Campus Home", url: "https://southerncompany-campus.jobs", category: "employer" },
  { id: "southwest-airlines-campus-reach", name: "Southwest Airlines — Campus Reach", url: "https://careers.southwestair.com/campus-reach", category: "employer" },
  { id: "spotify-students", name: "Spotify — Students", url: "https://lifeatspotify.com/start-your-journey/students", category: "employer" },
  { id: "starbucks-internships", name: "Starbucks — Internships", url: "https://careers.starbucks.com/discover-opportunities/internships", category: "employer" },
  { id: "state-street-careers-early-career-development", name: "State Street — Careers (early-career development)", url: "https://careers.statestreet.com/global/en", category: "employer" },
  { id: "stellantis-student-programs-internships-and-co-ops", name: "Stellantis — Student Programs: Internships and Co-ops", url: "https://careers.stellantis.com/early-careers/students-north-america", category: "employer" },
  { id: "stripe-emerging-talent", name: "Stripe — Emerging talent", url: "https://stripe.com/careers/emerging-talent", category: "employer" },
  { id: "stryker-students-and-graduates", name: "Stryker — Students and Graduates", url: "https://careers.stryker.com/students-and-graduates", category: "employer" },
  { id: "sig-events", name: "Susquehanna International Group — Susquehanna career events", url: "https://careers.sig.com/events", category: "employer" },
  { id: "susquehanna-international-group-susquehanna-discovery-days", name: "Susquehanna International Group — Susquehanna Discovery Days", url: "https://sig.com/careers/early-talent", category: "employer" },
  { id: "t-mobile-internships", name: "T-Mobile — Internships", url: "https://careers.t-mobile.com/internship", category: "employer" },
  { id: "target-career-events", name: "Target career events", url: "https://corporate.target.com/careers/events", category: "employer" },
  { id: "target-graduate-programs-internships", name: "Target — Graduate Programs & Internships", url: "https://corporate.target.com/careers/career-areas/intern-entry-level/graduate-programs-and-internships", category: "employer" },
  { id: "td-bank-students-new-grads", name: "TD Bank — Students & New Grads", url: "https://careers.td.com/student-new-grads", category: "employer" },
  { id: "tesla-internships", name: "Tesla Internships", url: "https://www.tesla.com/careers/internships", category: "employer" },
  { id: "the-cigna-group-students-graduates", name: "The Cigna Group — Students & Graduates", url: "https://jobs.thecignagroup.com/us/en/studentandgraduates", category: "employer" },
  { id: "the-hershey-company-interns", name: "The Hershey Company — Interns", url: "https://careers.thehersheycompany.com/go/Interns/9002600", category: "employer" },
  { id: "the-new-york-times-early-career-roles", name: "The New York Times — Early Career Roles", url: "https://www.nytco.com/careers/early-career-opportunities", category: "employer" },
  { id: "the-walt-disney-company-disney-programs", name: "The Walt Disney Company — Disney Programs", url: "https://jobs.disneycareers.com/disney-programs", category: "employer" },
  { id: "thomson-reuters-campus-careers", name: "Thomson Reuters — Campus Careers", url: "https://www.thomsonreuters.com/en/careers", category: "employer" },
  { id: "travelers-internships", name: "Travelers Internships", url: "https://careers.travelers.com/emerging-talent/internships", category: "employer" },
  { id: "truist-recruiting-events", name: "Truist — Recruiting Events", url: "https://careers.truist.com/us/en/events", category: "employer" },
  { id: "two-sigma-events", name: "Two Sigma events", url: "https://www.twosigma.com/careers/events", category: "employer" },
  { id: "two-sigma-careers-internships", name: "Two Sigma — Careers (Internships)", url: "https://www.twosigma.com/careers", category: "employer" },
  { id: "u-s-bank-career-fairs-and-conferences", name: "U.S. Bank — Career Fairs and Conferences", url: "https://careers.usbank.com/global/en/home", category: "employer" },
  { id: "u-s-department-of-energy-doe-stem-upcoming-events-and-deadlines", name: "U.S. Department of Energy — DOE STEM Upcoming Events and Deadlines", url: "https://www.energy.gov/doe-stem/upcoming-events-deadlines", category: "employer" },
  { id: "u-s-department-of-state-state-department-internships-and-fellowships", name: "U.S. Department of State — State Department Internships and Fellowships", url: "https://careers.state.gov/interns-fellows", category: "employer" },
  { id: "u-s-securities-and-exchange-commission-sec-students-and-recent-graduates", name: "U.S. Securities and Exchange Commission — SEC Students and Recent Graduates", url: "https://www.sec.gov/careers/students-and-recent-graduates", category: "employer" },
  { id: "ubs-early-careers-events", name: "UBS — Early Careers Events", url: "https://www.ubs.com/global/en/careers/early-careers/events.html", category: "employer" },
  { id: "unilever-early-careers", name: "Unilever — Early Careers", url: "https://careers.unilever.com/en/early-careers", category: "employer" },
  { id: "union-pacific-student-careers", name: "Union Pacific — Student Careers", url: "https://up.jobs/content/Students?locale=en_US", category: "employer" },
  { id: "united-airlines-aviate", name: "United Airlines — Aviate", url: "https://unitedaviate.com", category: "employer" },
  { id: "unitedhealth-group-early-careers", name: "UnitedHealth Group — Early Careers", url: "https://www.unitedhealthgroup.com/careers/en/work/early-careers.html", category: "employer" },
  { id: "ups-opportunities-for-students", name: "UPS — Opportunities for Students", url: "https://www.jobs-ups.com/us/en/opportunities-for-students", category: "employer" },
  { id: "usaa-university-internships-and-recruiting-events", name: "USAA University Internships and Recruiting Events", url: "https://www.usaajobs.com/university", category: "employer" },
  { id: "valero-intern-programs", name: "Valero — Intern Programs", url: "https://www.valero.com/careers/university-recruiting/intern-programs", category: "employer" },
  { id: "vanguard-student-programs", name: "Vanguard — Student Programs", url: "https://www.vanguardjobs.com/students", category: "employer" },
  { id: "veeva-systems-generation-veeva", name: "Veeva Systems — Generation Veeva", url: "https://www.veeva.com/generationveeva", category: "employer" },
  { id: "verizon-students-internships-early-in-career", name: "Verizon — Students & Internships / Early in Career", url: "https://mycareer.verizon.com/life-at-verizon/early-in-career", category: "employer" },
  { id: "virtu-financial-careers-interns-and-new-grads", name: "Virtu Financial — Careers (Interns and New Grads)", url: "https://www.virtu.com/careers", category: "employer" },
  { id: "visa-students-early-careers", name: "Visa Students + Early Careers", url: "https://corporate.visa.com/en/careers/early-careers.html", category: "employer" },
  { id: "walmart-students-development-programs", name: "Walmart Students & Development Programs", url: "https://careers.walmart.com/us/en/home/careers-areas/students", category: "employer" },
  { id: "warner-bros-discovery-global-intern-early-talent-programs", name: "Warner Bros. Discovery — Global Intern Early Talent Programs", url: "https://careers.wbd.com/global/en/global-intern-programs", category: "employer" },
  { id: "wells-fargo-early-careers-events", name: "Wells Fargo — Early Careers Events", url: "https://www.wellsfargojobs.com/en/early-careers/events", category: "employer" },
  { id: "xcel-energy-internships", name: "Xcel Energy — Internships", url: "https://jobs.xcelenergy.com/internships", category: "employer" },
  { id: "zillow-recruiting-events", name: "Zillow recruiting events", url: "https://www.zillow.com/careers/events", category: "employer" },
  { id: "zscaler-cyber-academy-for-students", name: "Zscaler Cyber Academy for Students", url: "https://www.zscaler.com/zscaler-cyber-academy", category: "employer" },

  // Professional organizations
  { id: "afrotech-conference-2026", name: "AfroTech Conference 2026", url: "https://afrotechconference.com", category: "professional_organization" },
  { id: "aises-national-conference-college-and-career-fair", name: "AISES National Conference – College and Career Fair", url: "https://conference.aises.org", category: "professional_organization" },
  { id: "american-chemical-society-acs-career-fair", name: "American Chemical Society — ACS Career Fair", url: "https://www.acs.org/events/fall/program/career-events.html", category: "professional_organization" },
  { id: "american-institute-of-chemical-engineers-aiche-annual-student-conference-recruitment-fair", name: "American Institute of Chemical Engineers — AIChE Annual Student Conference & Recruitment Fair", url: "https://www.aiche.org/conferences/annual-aiche-student-conference/2026/recruit-aiche", category: "professional_organization" },
  { id: "american-physical-society-aps-global-physics-summit-career-fair", name: "American Physical Society — APS Global Physics Summit Career Fair", url: "https://summit.aps.org/attend/career-fair", category: "professional_organization" },
  { id: "american-society-of-mechanical-engineers-asme-e-fest-careers", name: "American Society of Mechanical Engineers — ASME E-Fest Careers", url: "https://efests.asme.org", category: "professional_organization" },
  { id: "american-statistical-association-jsm-career-service", name: "American Statistical Association — JSM Career Service", url: "https://ww2.amstat.org/meetings/jsm/2026", category: "professional_organization" },
  { id: "anitab-org-grace-hopper-celebration-ghc-talent-tech-expo", name: "AnitaB.org — Grace Hopper Celebration (GHC) – Talent & Tech Expo", url: "https://ghc.anitab.org", category: "professional_organization" },
  { id: "association-for-supply-chain-management-ascm-virtual-career-fair", name: "Association for Supply Chain Management — ASCM Virtual Career Fair", url: "https://www.ascm.org/events", category: "professional_organization" },
  { id: "cae-cyber-ai-career-fair", name: "CAE Community — National Cyber and AI Virtual Career Fair", url: "https://www.caecommunity.org/national-cyber-and-ai-career-fair", category: "professional_organization" },
  { id: "cmd-it-acm-richard-tapia-conference-tapia-conference-college-career-fair", name: "CMD-IT / ACM Richard Tapia Conference — Tapia Conference College & Career Fair", url: "https://tapiaconference.cmd-it.org/become-a-partner", category: "professional_organization" },
  { id: "codepath-virtual-career-fairs", name: "CodePath Virtual Career Fairs", url: "https://www.codepath.org", category: "professional_organization" },
  { id: "colorstack-stacked-up-summit-colorstack-annual-career-fairs", name: "ColorStack — Stacked Up Summit / ColorStack Annual Career Fairs", url: "https://www.colorstack.org", category: "professional_organization" },
  { id: "equal-opportunity-publications-stem-diversity-virtual-career-fairs", name: "Equal Opportunity Publications — STEM Diversity Virtual Career Fairs", url: "https://www.eop.com/expos.php", category: "professional_organization" },
  { id: "great-minds-in-stem-gmis-gmis-annual-conference-career-graduate-school-fair", name: "Great Minds in STEM (GMiS) — GMiS Annual Conference – Career & Graduate School Fair", url: "https://gmisconference.org", category: "professional_organization" },
  { id: "hiring-our-heroes-events", name: "Hiring Our Heroes Events", url: "https://events.hiringourheroes.org", category: "professional_organization" },
  { id: "ieee-virtual-career-fair-series", name: "IEEE Virtual Career Fair Series", url: "https://careerfair.ieee.org", category: "professional_organization" },
  { id: "informs-2026-annual-meeting-career-fair", name: "INFORMS 2026 Annual Meeting Career Fair", url: "https://careercenter.informs.org/events/INFORMS_2026_Annual_Meeting_Career_Fair-3", category: "professional_organization" },
  { id: "national-black-mba-association-nbmbaa-nbmbaa-annual-conference-and-career-expo", name: "National Black MBA Association (NBMBAA) — NBMBAA Annual Conference and Career Expo", url: "https://nbmbaa.org/2026-career-expo", category: "professional_organization" },
  { id: "national-retail-federation-foundation-nrf-foundation-student-program", name: "National Retail Federation Foundation — NRF Foundation Student Program", url: "https://nrffoundation.org/campus/new-york", category: "professional_organization" },
  { id: "national-sales-network-nsn-professional-conference-and-career-fair", name: "National Sales Network — NSN Professional Conference and Career Fair", url: "https://conference.salesnetwork.org", category: "professional_organization" },
  { id: "national-society-of-black-engineers-nsbe-nsbe-annual-convention-nextgen-innovation-expo", name: "National Society of Black Engineers (NSBE) — NSBE Annual Convention / NextGen Innovation Expo", url: "https://convention.nsbe.org", category: "professional_organization" },
  { id: "ostem-annual-conference-career-graduate-school-expo", name: "oSTEM Annual Conference – Career & Graduate School Expo", url: "https://conference.ostem.org", category: "professional_organization" },
  { id: "prospanica-national-conference-career-expo", name: "Prospanica National Conference & Career Expo", url: "https://prospanica.org/conference2026", category: "professional_organization" },
  { id: "rewriting-the-code-rtc-events-calendar-career-employer-events", name: "Rewriting the Code — RTC Events Calendar – Career & Employer Events", url: "https://rewritingthecode.org/events-page", category: "professional_organization" },
  { id: "rsa-conference-rsac-college-day", name: "RSA Conference — RSAC College Day", url: "https://www.rsaconference.com/usa/programs/college-day", category: "professional_organization" },
  { id: "sacnas-national-diversity-in-stem-ndistem-conference-academic-career-expo", name: "SACNAS National Diversity in STEM (NDiSTEM) Conference – Academic & Career Expo", url: "https://www.sacnas.org/exhibiting", category: "professional_organization" },
  { id: "sae-international-sae-new-mobility-virtual-career-fair", name: "SAE International — SAE New Mobility Virtual Career Fair", url: "https://www.sae.org/attend/new-mobility-virtual-career-fair", category: "professional_organization" },
  { id: "society-for-industrial-and-applied-mathematics-siam-career-fairs", name: "Society for Industrial and Applied Mathematics — SIAM Career Fairs", url: "https://www.siam.org/conferences-events/siam-conferences/career-fairs", category: "professional_organization" },
  { id: "society-of-hispanic-professional-engineers-shpe-shpe-national-convention", name: "Society of Hispanic Professional Engineers (SHPE) — SHPE National Convention", url: "https://shpe.org/2026-shpe", category: "professional_organization" },
  { id: "society-of-women-engineers-swe-we26-annual-conference-career-fair", name: "Society of Women Engineers (SWE) — WE26 Annual Conference / Career Fair", url: "https://we26.swe.org", category: "professional_organization" },
  { id: "spie-photonics-west-career-hub-and-job-fair", name: "SPIE Photonics West Career Hub and Job Fair", url: "https://spie.org/conferences-and-exhibitions/photonics-west/career-hub", category: "professional_organization" },
  { id: "women-in-cybersecurity-wicys-wicys-annual-conference-career-fair", name: "Women in CyberSecurity (WiCyS) — WiCyS Annual Conference – Career Fair", url: "https://www.wicys.org/event/wicys-2027-annual-conference", category: "professional_organization" },

  // Event platforms
  { id: "caci-international-events", name: "CACI International Events", url: "https://app.eightfold.ai/events/open?domain=caci.com", category: "event_platform" },
  { id: "careereco-upcoming-fairs", name: "CareerEco — Upcoming Fairs", url: "https://www.careereco.com/Fair/UpcomingFairs", category: "event_platform" },
  { id: "careermd-career-fair-schedule", name: "CareerMD Career Fair Schedule", url: "https://app.careermd.com/physicians/searchforevents.aspx", category: "event_platform" },
  { id: "choice-career-fairs-upcoming-career-fairs", name: "Choice Career Fairs — Upcoming Career Fairs", url: "https://choicecareerfairs.com/career-fairs", category: "event_platform" },
  { id: "indeed-events", name: "Indeed Events", url: "https://www.indeedevents.com", category: "event_platform" },
  { id: "jobfairx-2026-job-fair-hiring-event-calendar", name: "JobFairX — 2026 Job Fair & Hiring Event Calendar", url: "https://jobfairx.com/job-fair-calendar", category: "event_platform" },
  { id: "powertofly-events", name: "PowerToFly Events", url: "https://powertofly.com/events", category: "event_platform" },
  { id: "recruitmilitary-veteran-job-fairs", name: "RecruitMilitary — Veteran Job Fairs", url: "https://my.recruitmilitary.com/events/schedule", category: "event_platform" },
  { id: "society-of-asian-scientists-and-engineers-sase-stem-connect-sase-national-convention-career-fair", name: "Society of Asian Scientists and Engineers (SASE) — STEM Connect / SASE National Convention Career Fair", url: "https://stemconnect.events", category: "event_platform" },
  { id: "usajobs-events", name: "USAJOBS Events", url: "https://www.usajobs.gov/event", category: "event_platform" },
]);
