import type { RecruitingEventSource } from "./repository.ts";

export const RECRUITING_EVENT_SOURCES: readonly RecruitingEventSource[] = Object.freeze([
  { id: "ibm-z-skills-fest", name: "IBM Z Skills Fest", url: "https://www.ibm.com/community/z/skillsfest/", category: "employer" },
  { id: "lockheed-martin-events", name: "Lockheed Martin career events", url: "https://www.lockheedmartin.com/en-us/careers/events.html", category: "employer" },
  { id: "blackrock-student-events", name: "BlackRock student events", url: "https://careers.blackrock.com/students-and-graduates-events", category: "employer" },
  { id: "wells-fargo-events", name: "Wells Fargo career events", url: "https://www.wellsfargojobs.com/en/events/", category: "employer" },
  { id: "target-career-events", name: "Target career events", url: "https://corporate.target.com/careers/events", category: "employer" },
  { id: "bristol-myers-squibb-events", name: "Bristol Myers Squibb career events", url: "https://careers.bms.com/events/", category: "employer" },
  { id: "capital-one-events", name: "Capital One career events", url: "https://www.capitalonecareers.com/events", category: "employer" },
  { id: "jpmorgan-student-events", name: "JPMorganChase student events", url: "https://careers.jpmorgan.com/us/en/students/events", category: "employer" },
  { id: "morgan-stanley-events", name: "Morgan Stanley student events", url: "https://www.morganstanley.com/people-opportunities/students-graduates/events", category: "employer" },
  { id: "goldman-sachs-events", name: "Goldman Sachs student programs", url: "https://www.goldmansachs.com/careers/students/programs-and-internships", category: "employer" },
  { id: "microsoft-events", name: "Microsoft university virtual events", url: "https://careers.microsoft.com/v2/global/en/virtualevents", category: "employer" },
  { id: "google-student-events", name: "Google student events", url: "https://buildyourfuture.withgoogle.com/events", category: "employer" },
  { id: "jane-street-events", name: "Jane Street events", url: "https://www.janestreet.com/join-jane-street/events/", category: "employer" },
  { id: "sig-events", name: "Susquehanna career events", url: "https://careers.sig.com/events/", category: "employer" },
  { id: "imc-student-events", name: "IMC student events", url: "https://www.imc.com/us/careers/students-graduates/events", category: "employer" },
  { id: "akuna-students", name: "Akuna Capital student opportunities", url: "https://akunacapital.com/careers/students", category: "employer" },
  { id: "citadel-students", name: "Citadel student opportunities", url: "https://www.citadel.com/careers/students/", category: "employer" },
  { id: "drw-students", name: "DRW student opportunities", url: "https://www.drw.com/work-at-drw/students", category: "employer" },
  { id: "two-sigma-events", name: "Two Sigma events", url: "https://www.twosigma.com/careers/events/", category: "employer" },
  { id: "bloomberg-events", name: "Bloomberg career events", url: "https://bloomberg.avature.net/events/EventsList", category: "employer" },
  { id: "ieee-global-career-fair", name: "IEEE Global Career Fair", url: "https://careerfair.ieee.org/", category: "professional_organization" },
  { id: "tapia-conference", name: "Tapia Conference", url: "https://tapiaconference.cmd-it.org/", category: "professional_organization" },
  { id: "sase-conference", name: "SASE National Convention", url: "https://conference.saseconnect.org/", category: "professional_organization" },
  { id: "grace-hopper-celebration", name: "Grace Hopper Celebration", url: "https://ghc.anitab.org/", category: "professional_organization" },
  { id: "shpe-convention", name: "SHPE National Convention", url: "https://convention.shpe.org/", category: "professional_organization" },
  { id: "swe-we26", name: "SWE WE26", url: "https://we26.swe.org/", category: "professional_organization" },
  { id: "cae-cyber-ai-career-fair", name: "National Cyber and AI Virtual Career Fair", url: "https://www.caecommunity.org/national-cyber-and-ai-career-fair", category: "professional_organization" },
  { id: "careereco-fairs", name: "CareerEco virtual fairs", url: "https://www.careereco.com/Fair/EventDetails", category: "event_platform" },
]);
